"""adiciona valor_minimo no investmentplan

Revision ID: 17e3c8fb96c1
Revises: 8352f5caee43
Create Date: 2025-08-01 15:31:44.905527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e3c8fb96c1'
down_revision = '8352f5caee43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_minimo', sa.Float(), nullable=False, server_default='5000'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('multicaixa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multicaixa', sa.VARCHAR(length=9), nullable=True))

    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.drop_column('valor_minimo')

    # ### end Alembic commands ###
