"""ativo InvestmentPlan

Revision ID: 25655aa91cff
Revises: b7af92881edf
Create Date: 2025-08-06 00:38:06.363025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25655aa91cff'
down_revision = 'b7af92881edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invest', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rendimento_diario', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('retorno_total', sa.Float(), nullable=False))
        batch_op.drop_column('duration_days')
        batch_op.drop_column('daily_return_percent')
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('daily_return_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('retorno_total')
        batch_op.drop_column('rendimento_diario')
        batch_op.drop_column('invest')

    # ### end Alembic commands ###
