"""adicionar campos

Revision ID: 2e6894862a13
Revises: bdbb56b1bfdd
Create Date: 2025-08-11 20:05:13.807252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6894862a13'
down_revision = 'bdbb56b1bfdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxa', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_liquido', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal', schema=None) as batch_op:
        batch_op.drop_column('valor_liquido')
        batch_op.drop_column('taxa')

    # ### end Alembic commands ###
