"""ativo InvestmentPlan

Revision ID: 41d7b6834f9b
Revises: e211da060695
Create Date: 2025-08-06 17:13:40.753044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d7b6834f9b'
down_revision = 'e211da060695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_minimo', sa.Float(), nullable=False, server_default='5000'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.drop_column('valor_minimo')

    # ### end Alembic commands ###
