"""ativo InvestmentPlan

Revision ID: b203bbd28936
Revises: 9d4e9998ab0d
Create Date: 2025-08-06 00:19:16.565285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b203bbd28936'
down_revision = '9d4e9998ab0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=False))
        batch_op.drop_column('min_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('valor')

    # ### end Alembic commands ###
