"""ativo InvestmentPlan

Revision ID: b7af92881edf
Revises: b203bbd28936
Create Date: 2025-08-06 00:29:32.737069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7af92881edf'
down_revision = 'b203bbd28936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=50), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
