"""adicionar campos

Revision ID: bdbb56b1bfdd
Revises: db07c10937ef
Create Date: 2025-08-11 19:37:56.011451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbb56b1bfdd'
down_revision = 'db07c10937ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recebido', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.drop_column('recebido')

    # ### end Alembic commands ###
